title: Patrick Silva
# logo: /assets/img/headshot_circle.png
description: Este portfólio reúne meus principais projetos em Ciência de Dados, nos quais aplico técnicas de análise de dados, estatística, visualização e Machine Learning para resolver problemas reais de negócio.


show_downloads: true
theme: jekyll-theme-minimal
